import { useEffect, useState, type ReactNode, type FormEvent } from 'react';

import type { CompetitionSession as Session, SecurityEvent as Event } from '../security/securityTypes';
const labels: Record<string, string> = { PAGE_HIDDEN: 'Browser tab became hidden', WINDOW_BLUR: 'Browser lost focus', FULLSCREEN_EXIT: 'Fullscreen was exited', SESSION_INTERRUPTED: 'Session interrupted', COMPETITION_STARTED: 'Competition started', STAFF_UNLOCK: 'Staff unlocked competition', INVALID_STAFF_PIN: 'Incorrect staff PIN', SESSION_RESET: 'Session reset', CROSS_TAB_CONFLICT: 'Session changed in another tab', STORAGE_FAILURE: 'Session storage failed' };
const human = (value: string) => labels[value] ?? value.replaceAll('_', ' ').toLowerCase();
const time = (value?: string) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : '—';

export function SecurityStatus({ session }: { session: Session }) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const seconds = session.startedAt ? Math.max(0, Math.floor((now - Date.parse(session.startedAt)) / 1000)) : 0;
  const elapsed = Number.isFinite(seconds) ? `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}` : '00:00';
  return <div className="status-strip" data-testid="session-state" aria-label="Competition status"><div><span className={`status-dot ${session.status.toLowerCase()}`} /><span>Competition Mode: <strong>{session.status.replaceAll('_', ' ')}</strong></span></div><div><span className="metric-label">Elapsed</span><strong className="mono">{elapsed}</strong></div><div><span className="metric-label">Fullscreen</span><strong>{document.fullscreenElement ? 'On' : 'Off'}</strong></div><div><span className="metric-label">Security events</span><strong>{session.eventCount}</strong></div></div>;
}

export function LandingScreen({ busy, healthy, onStart }: { busy: boolean; healthy: boolean; onStart: () => Promise<void> }) {
  return <section className="landing-layout"><div className="hero-copy"><p className="eyebrow">READY TO EXPLORE</p><h1>A little chemistry.<br /><em>A lot of possibility.</em></h1><p className="lead">Welcome to the SJS Olympiad competition security test.</p><p>This device will enter Competition Mode. Once started, leaving fullscreen, changing browser tab or switching away from the competition will lock the device.</p><button className="button primary enter-button" disabled={busy || !healthy} onClick={() => { void onStart(); }}>{busy ? 'Entering fullscreen…' : 'Enter Competition Mode'}<span aria-hidden="true">↗</span></button><p className="button-note">Fullscreen is required. Your session begins only after it succeeds.</p></div><aside className="preflight-card"><div className="atom-art" aria-hidden="true"><span className="orbit orbit-one" /><span className="orbit orbit-two" /><span className="orbit orbit-three" /><span className="nucleus" /></div><p className="eyebrow">YOUR COMPETITION SPACE</p><h2>Stay in the element.</h2><p>Once Competition Mode starts, keep this window open and focused.</p><ul className="rules-list"><li>Stay in fullscreen</li><li>Keep this browser tab selected</li><li>Do not minimise or switch applications</li></ul><div className="staff-note">If the device locks, a member of staff will help you resume.</div></aside></section>;
}

export function CompetitionScreen() {
  const [answer, setAnswer] = useState<string | null>(null);
  return <section className="question-card" data-testid="question-content" aria-labelledby="question-title"><div className="question-heading"><span className="eyebrow">THEORY · DEMONSTRATION</span><span className="question-number">01 / 01</span></div><h1 id="question-title">Which element has the highest<br className="desktop-break" /> first ionisation energy?</h1><p className="question-description">Select one element below.</p><div className="answers" role="group" aria-label="Answer choices">{[{ letter: 'A', symbol: 'Na', name: 'Sodium', number: 11 }, { letter: 'B', symbol: 'Mg', name: 'Magnesium', number: 12 }, { letter: 'C', symbol: 'Al', name: 'Aluminium', number: 13 }, { letter: 'D', symbol: 'Si', name: 'Silicon', number: 14 }].map(element => <button key={element.symbol} className={`element-option ${answer === element.symbol ? 'selected' : ''}`} aria-pressed={answer === element.symbol} onClick={() => setAnswer(element.symbol)}><span className="option-letter">{element.letter}</span><span className="atomic-number">{element.number}</span><strong className="element-symbol">{element.symbol}</strong><span>{element.name}</span><span className="selection-indicator" aria-hidden="true">{answer === element.symbol ? '✓' : '+'}</span></button>)}</div><p className="answer-feedback" role="status">{answer ? `${answer} selected. This demonstration does not mark or score answers.` : 'Demonstration question · No score is recorded.'}</p><div className="question-footer"><span className="status-dot active" />Competition Mode is active. Keep this window focused and in fullscreen.</div></section>;
}

export function LockScreen({ session, busy, onUnlock }: { session: Session; busy: boolean; onUnlock: (pin: string) => Promise<void> }) {
  const [pin, setPin] = useState('');
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const entered = pin; setPin(''); void onUnlock(entered); }
  return <section className="lock-card" aria-labelledby="lock-title"><div className="lock-icon" aria-hidden="true">▣</div><p className="eyebrow">STAFF ASSISTANCE REQUIRED</p><h1 id="lock-title">Competition locked</h1><p className="lead">This device has left Competition Mode.</p><p>The question has been removed. A member of staff must unlock this device before you can continue.</p><dl className="lock-details"><div><dt>Reason</dt><dd>{session.lockReason ? human(session.lockReason) : 'Session requires staff recovery'}</dd></div><div><dt>Time</dt><dd className="mono">{time(session.lockedAt)}</dd></div></dl><form className="unlock-form" onSubmit={submit}><label htmlFor="staff-pin">Staff unlock PIN</label><div className="unlock-controls"><input id="staff-pin" type="password" inputMode="numeric" autoComplete="off" value={pin} onChange={event => setPin(event.target.value)} disabled={busy} placeholder="Enter staff PIN" aria-describedby="unlock-note" /><button className="button primary" disabled={busy || !pin.trim()}>{busy ? 'Restoring fullscreen…' : 'Unlock Competition'}<span aria-hidden="true">↗</span></button></div><p id="unlock-note">Unlocking restores fullscreen before the question returns.</p></form></section>;
}

export function Diagnostics({ events, storageHealthy, children }: { events: Event[]; storageHealthy: boolean; children?: ReactNode }) {
  const [tick, setTick] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setTick(value => value + 1), 1000); return () => clearInterval(timer); }, []);
  void tick;
  return <details className="diagnostics"><summary><span>Security diagnostics <small>Testing only</small></span><span className="diagnostic-count">{events.length} events</span></summary><div className="diagnostics-content"><dl className="browser-facts"><div><dt>Viewport</dt><dd>{window.innerWidth} × {window.innerHeight}</dd></div><div><dt>Fullscreen supported</dt><dd>{document.fullscreenEnabled ? 'Yes' : 'No'}</dd></div><div><dt>Visibility</dt><dd>{document.visibilityState}</dd></div><div><dt>Window focused</dt><dd>{document.hasFocus() ? 'Yes' : 'No'}</dd></div><div><dt>Fullscreen active</dt><dd>{document.fullscreenElement ? 'Yes' : 'No'}</dd></div><div><dt>Session storage</dt><dd>{storageHealthy ? 'Available' : 'Unavailable / invalid'}</dd></div><div className="user-agent"><dt>Browser user agent</dt><dd>{navigator.userAgent}</dd></div></dl><div className="event-table-wrap"><table><caption className="sr-only">Security event log, newest first</caption><thead><tr><th scope="col">Time</th><th scope="col">Event</th></tr></thead><tbody>{events.length ? [...events].reverse().map(event => <tr key={event.id}><td className="mono"><time dateTime={event.at}>{time(event.at)}</time></td><td>{human(event.type)}{event.reason && <small>{human(event.reason)}</small>}{event.relatedSignals && event.relatedSignals.length > 0 && <small>Related signals: {[...new Set(event.relatedSignals)].map(human).join(' · ')}</small>}</td></tr>) : <tr><td colSpan={2}>No security events recorded yet.</td></tr>}</tbody></table></div>{children}<p className="diagnostic-disclaimer">Browser detection test only. Local session state and the test PIN can be inspected or changed; this is not secure examination lockdown.</p></div></details>;
}
